(() => {
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={brief:'의뢰 접수',facts:'콘셉트 선택',strategy:'콘셉트 선택',concepts:'콘셉트 선택',develop:'제작 설계',storyboard:'콘티 확인',anchors:'영상 제작',video:'영상 제작',post:'영상 제작',deliver:'납품'};   // 광고주 화면 6칸과 같은 이름 (09-23)
 const asking=new Set();
 // 상태 색 — 빨강: 광고주가 할 일 · 파랑: 진행 중 · 초록: 끝남 (brand.css)
 const stClass=t=>/부탁|차례|확인하실/.test(t)?'st-act':/완료/.test(t)?'st-done':/수정|다시/.test(t)?'st-fix':'st-run';   // 우리가 보낸 메시지에 아직 답이 없는 건 — 「답변 부탁드립니다」
 let rows=[],filter='all',query='',signedIn=false;
 const box=document.querySelector('#dashboard-projects');
 const isDone=p=>p.state==='done'||(p.step==='deliver'&&p.state==='idle');
 const state=p=>asking.has(p.id)?'답변 부탁드립니다':p.state==='done'?'완료':p.step==='deliver'&&p.state==='idle'?'승인 완료':p.step==='deliver'&&p.state==='ready'?'납품 확인하실 차례':p.state==='ready'?'검토 대기':p.step==='deliver'?'납품 준비 중':p.step==='brief'?'의뢰 확인 중':['facts','strategy','concepts'].includes(p.step)?'콘셉트 준비 중':'제작 진행';
 function render(){if(!signedIn)return;const show=rows.filter(p=>(filter==='all'||(filter==='done'?isDone(p):filter==='ready'?p.state==='ready':p.state==='pending'))&&`${p.brand} ${p.product}`.toLowerCase().includes(query.toLowerCase()));box.innerHTML=show.length?`<table class="studio-table"><thead><tr><th>프로젝트</th><th>진행 단계</th><th>상태</th><th>영상 규격</th><th>최근 변경</th><th></th></tr></thead><tbody>${show.map(p=>`<tr><td><a href="project.html?slug=${encodeURIComponent(p.slug)}"><b>${esc(p.brand||p.slug)}</b><small>${esc(p.product)}</small></a></td><td>${p.state==='done'?'완료':(names[p.step]||esc(p.step))}</td><td><span class="tag ${stClass(state(p))}">${state(p)}</span></td><td>${Number(p.running_sec)||'—'}초 · ${esc(p.aspect||'미정')}</td><td>${esc(p.updated_at?.slice(0,10)||'')}</td><td><a href="project.html?slug=${encodeURIComponent(p.slug)}" aria-label="${esc(p.brand)} 프로젝트 열기">↗</a></td></tr>`).join('')}</tbody></table>`:'<div class="empty">표시할 프로젝트가 없습니다. <a class="btn ghost" href="new.html">새 프로젝트 시작</a></div>';}
 function stats(){for(const [id,n] of [['total',rows.length],['working',rows.filter(p=>p.state==='pending').length],['waiting',rows.filter(p=>p.state==='ready').length],['finished',rows.filter(isDone).length]])document.getElementById(id).textContent=String(n).padStart(2,'0');}
 async function boot(){try{const db=window.ONECUE_DB||(window.ONECUE_DB=window.supabase.createClient(ONECUE.supabaseUrl,ONECUE.supabaseAnonKey));const {data:{user}}=await db.auth.getUser();if(!user){document.querySelector('#conn').textContent='로그인 전';box.innerHTML='<div class="studio-signin"><div><h3>진행 중인 프로젝트를 확인하세요.</h3><p>로그인하면 의뢰와 검토 내역이 이어집니다.</p></div><a class="btn" href="login.html?next=studio.html">로그인 →</a></div>';return;}signedIn=true;const {data:profile,error:profileError}=await db.from('profiles').select('is_admin,admin_can_write,name').eq('id',user.id).maybeSingle();if(profileError)throw profileError;document.querySelector('#greeting').textContent=`${profile?.name||'고객'}님, 오늘의 프로젝트를 확인해 보세요.`;let result;
 if(profile?.is_admin&&profile?.admin_can_write){result=await db.from('projects').select('id,slug,brand,product,step,state,running_sec,aspect,updated_at').order('updated_at',{ascending:false});rows=result.data||[];}
 else {result=await db.from('projects').select('id,slug,brand,product,step,state,running_sec,aspect,updated_at,clients!inner(owner_id)').eq('clients.owner_id',user.id).order('updated_at',{ascending:false});rows=result.data||[];}
 if(result.error)throw result.error;asking.clear();if(rows.length){const m=await db.from('project_messages').select('project_id,author,sent_at').in('project_id',rows.map(r=>r.id)).not('sent_at','is',null).order('sent_at');const last={};(m.data||[]).forEach(x=>{last[x.project_id]=x.author;});Object.keys(last).forEach(k=>{if(last[k]==='admin')asking.add(k);});}document.querySelector('#conn').textContent='연결됨';stats();render();
 }catch(e){document.querySelector('#conn').textContent='연결 확인 필요';box.innerHTML='<div class="empty">프로젝트를 불러오지 못했습니다. 잠시 후 새로고침해 주세요.</div>';}}
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render();});
 document.querySelector('#project-search').oninput=e=>{query=e.target.value;render();};
 document.querySelector('#find-project').onsubmit=e=>{e.preventDefault();let value=e.target.elements.slug.value.trim();try{if(value.includes('://')){const u=new URL(value);if(u.origin!==location.origin)throw Error();value=u.searchParams.get('slug')||'';}if(!value||value.length>200||/[<>\s/?#]/.test(value))throw Error();location.href='project.html?slug='+encodeURIComponent(value);}catch{e.target.elements.slug.setCustomValidity('ONECUE 프로젝트 주소 또는 코드를 입력해 주세요.');e.target.elements.slug.reportValidity();}};
 document.querySelector('#find-project input').oninput=e=>e.target.setCustomValidity('');boot();
})();
